name: my_linter
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies and pytest
        run: |
          pip install poetry
          make install
          poetry add pytest
      - name: Run linter and test
        run: |
          make check
