name: my_linter
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies and pytest
        run: |
          pip install poetry
          make install
          poetry add pytest
      - name: Run linter
        run: |
          make lint
      - name: Coverage-report
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: 0c08b7f3b51ef449eb478820e9c95df330bbc0a312b946d822c4be3ebaa3c013
        with:
          coverageCommand: |
            make testing
            make coverage
